using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

[Generator]
public class LoggGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var loggedTypes = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (s, _) => s is InvocationExpressionSyntax,
            transform: static (ctx, _) =>
            {
                if (ctx.Node is not InvocationExpressionSyntax invocation) return null;
                var symbol = ctx.SemanticModel.GetSymbolInfo(invocation).Symbol as IMethodSymbol;
                if (symbol != null && symbol.Name == "Write" && symbol.ContainingType.Name == "Logg" && symbol.ContainingNamespace.ToDisplayString() == "MoT")
                {
                    if (symbol.IsGenericMethod && symbol.TypeArguments.Length > 0) return symbol.TypeArguments[0];
                    if (!symbol.IsGenericMethod && symbol.Parameters.Length > 0) return symbol.Parameters[0].Type;
                }
                return null;
            })
            .Where(static t => t is not null)
            .Collect();

        context.RegisterSourceOutput(loggedTypes, static (spc, types) =>
        {
            var uniqueTypes = types.Distinct(SymbolEqualityComparer.Default).Cast<INamedTypeSymbol>().ToList();
            if (uniqueTypes.Count == 0) return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using Microsoft.Data.Sqlite;");
            sb.AppendLine("using System.Text.Json;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine();
            sb.AppendLine("namespace MoT");
            sb.AppendLine("{");

            // 1. 生成注册器 (在程序启动时同步建表)
            sb.AppendLine("    internal static class LoggRegistrar");
            sb.AppendLine("    {");
            sb.AppendLine("        [ModuleInitializer]");
            sb.AppendLine("        internal static void Initialize()");
            sb.AppendLine("        {");
            foreach (var type in uniqueTypes)
            {
                string fullName = type.ToDisplayString();
                string safeName = GetSafeName(type);
                // 传入表名和建表 SQL，在启动时立即建表
                sb.AppendLine($"            Logg.Register<{fullName}>({safeName}_Writer.Write, \"{safeName}\", {safeName}_Writer.CreateTableSql);");
            }
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            // 2. 为每个类型生成独立的 Writer 类
            foreach (var type in uniqueTypes)
            {
                GenerateSpecificWriter(sb, type);
            }

            sb.AppendLine("}");
            spc.AddSource("Logg.Generated.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }

    private static void GenerateSpecificWriter(StringBuilder sb, INamedTypeSymbol type)
    {
        string fullName = type.ToDisplayString();
        string safeName = GetSafeName(type);

        var props = type.GetMembers().OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic && !p.IsIndexer).ToList();

        sb.AppendLine($"    internal static class {safeName}_Writer");
        sb.AppendLine("    {");

        // --- 生成格式化的 CreateTable SQL (改为 internal 供 Registrar 访问) ---
        sb.AppendLine("        internal const string CreateTableSql = @\"");
        sb.AppendLine($"            CREATE TABLE IF NOT EXISTS [{safeName}] (");
        sb.AppendLine("                [_t_] TEXT NOT NULL,");
        for (int i = 0; i < props.Count; i++)
        {
            string comma = i == props.Count - 1 ? "" : ",";
            sb.AppendLine($"                [{props[i].Name}] {GetSqliteType(props[i].Type)}{comma}");
        }
        sb.AppendLine("            );\";");
        sb.AppendLine();

        // --- 生成格式化的 Insert SQL ---
        var cols = string.Join(", ", props.Select(p => $"[{p.Name}]"));
        var pars = string.Join(", ", props.Select(p => $"@{p.Name}"));
        sb.AppendLine("        private const string InsertSql = @\"");
        sb.AppendLine($"            INSERT INTO [{safeName}] ([_t_], {cols})");
        sb.AppendLine($"            VALUES (@_t_, {pars});\";");
        sb.AppendLine();

        // --- 生成 Write 方法 (移除 CreateTableSql) ---
        sb.AppendLine($"        public static void Write({fullName} v)");
        sb.AppendLine("        {");
        sb.AppendLine($"            Logg.Enqueue(new LogJob(InsertSql, cmd => BindParameters(cmd, v)));");
        sb.AppendLine("        }");
        sb.AppendLine();

        // --- 生成 BindParameters 方法 ---
        sb.AppendLine($"        private static void BindParameters(SqliteCommand cmd, {fullName} v)");
        sb.AppendLine("        {");
        sb.AppendLine("            cmd.Parameters.Clear();");
        sb.AppendLine("            cmd.Parameters.AddWithValue(\"@_t_\", DateTime.Now.ToString(\"o\"));");
        foreach (var p in props)
            sb.AppendLine($"            cmd.Parameters.AddWithValue(\"@{p.Name}\", {GetValExpr(p, "v")});");
        sb.AppendLine("        }");

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static string GetSafeName(INamedTypeSymbol type) => type.Name + (type.TypeArguments.Length > 0 ? "_" + type.TypeArguments[0].Name : "");

    private static string GetValExpr(IPropertySymbol p, string e) =>
        p.Type.SpecialType == SpecialType.None && p.Type.TypeKind != TypeKind.Enum && p.Type.TypeKind != TypeKind.Struct && p.Type.Name != "String" && p.Type.Name != "DateTime"
        ? $"{e}.{p.Name} == null ? DBNull.Value : JsonSerializer.Serialize({e}.{p.Name})" : $"{e}.{p.Name} == null ? DBNull.Value : {e}.{p.Name}";

    private static string GetSqliteType(ITypeSymbol t)
    {
        if (t.SpecialType == SpecialType.System_String) return "TEXT";
        if (t.TypeKind == TypeKind.Enum) return "INTEGER";
        if (t.SpecialType is SpecialType.System_Int32 or SpecialType.System_Int64 or SpecialType.System_Int16 or SpecialType.System_Byte or SpecialType.System_Boolean) return "INTEGER";
        if (t.SpecialType is SpecialType.System_Single or SpecialType.System_Double or SpecialType.System_Decimal) return "REAL";
        return "TEXT";
    }
}