<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>FMO.Disclosure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="DateTemplateAutoLoader.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Utility\SourceGenerator\SourceGenerator.csproj" OutputItemType="Analyzer" />
    <ProjectReference Include="..\Disclosure\Disclosure.csproj" />
  </ItemGroup>

  <ItemGroup>

    <PackageReference Include="HandyControl" Version="3.5.1" />
  </ItemGroup>
</Project>
