<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
	  <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Page Include="dt.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup> 
		<ProjectReference Include="..\..\Utility\SourceGenerator\SourceGenerator.csproj" OutputItemType="Analyzer"  ReferenceOutputAssembly="false" /> 
		<ProjectReference Include="..\Trustee\Trustee.csproj" />
	</ItemGroup>
</Project>
