<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MoT.Logg" Version="1.1.8" />
    <PackageReference Include="RapidOCRSharpOnnx" Version="1.0.7" />
  </ItemGroup>
	<ItemGroup>
	  <None Update="modelfiles\ch_PP-LCNet_x0_25_textline_ori_cls_mobile.onnx">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="modelfiles\ch_PP-OCRv5_det_mobile.onnx">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="modelfiles\ch_PP-OCRv5_rec_mobile.onnx">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>
</Project>
