<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="JsonModels\ManagerInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Playwright" Version="1.59.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Main\Models\Models.csproj" />
    <ProjectReference Include="..\..\Utility\OCR\OCR.csproj" />
    <ProjectReference Include="..\..\Utility\FileTemplate\FileTemplate.csproj" />
    <ProjectReference Include="..\..\Utility\Utilities\Utilities.csproj" />
    <ProjectReference Include="..\Public\Amac.Public.csproj" />
  </ItemGroup>

</Project>
