<Project>


  <!-- 🟢 强签名配置（单行定义，仅当 CI 传入密钥路径时生效，本地构建自动跳过） -->
  <PropertyGroup Condition="'$(STRONG_KEY_PATH)' != ''">
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>$(STRONG_KEY_PATH)</AssemblyOriginatorKeyFile>
    <PublicSign Condition=" '$([MSBuild]::IsOSPlatform(Windows))' == 'false' ">true</PublicSign>
  </PropertyGroup>
  

</Project>