<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Rules\**" />
    <EmbeddedResource Remove="Rules\**" />
    <None Remove="Rules\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="DataObserbler.cs" />
    <Compile Remove="IDataValidation.cs" />
    <Compile Remove="VerifyRules.cs" />
  </ItemGroup>

  <ItemGroup> 
    <ProjectReference Include="..\..\Utility\Utilities\Utilities.csproj" />
	  <ProjectReference Include="..\..\Utility\Logging\Logging.csproj" />
	  <ProjectReference Include="..\..\Utility\SourceGenerator\SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	  <ProjectReference Include="..\HookableGenerator\ModelsGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
