using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices.ComTypes;
using System.Text;

namespace MissionTemplateGenerator;

[Generator]
public class MissionRegistrationGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. 收集编译中的所有类型
        var allTypesProvider = context.CompilationProvider.Select((compilation, _) =>
        {
            var list = new List<INamedTypeSymbol>();
            CollectTypes(compilation.GlobalNamespace, list);
            return list;
        });

        // 2. 过滤并配对 Mission 与 ViewModel
        var matchedPairsProvider = allTypesProvider.Select((types, _) =>
        {
            var missions = types.Where(t => InheritsFrom(t, "Mission")).ToList();
            var vmMap = new Dictionary<INamedTypeSymbol, INamedTypeSymbol>(SymbolEqualityComparer.Default);

            foreach (var t in types)
            {
                if (TryGetMissionFromViewModel(t, out var missionType))
                {
                    vmMap[missionType] = t;
                }
            }

            // 仅生成存在对应 ViewModel 的 Mission
            return missions
                .Where(m => vmMap.TryGetValue(m, out var v))
                .OrderBy(m => m.Name) // 保证生成顺序稳定
                .Select(m => (Mission: m, ViewModel: vmMap[m]))
                .ToList();
        });

        // 3. 输出源码
        context.RegisterSourceOutput(matchedPairsProvider, (ctx, pairs) =>
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using FMO.Schedule;");
            sb.AppendLine();
            sb.AppendLine("public static class MissionTemplateManager");
            sb.AppendLine("{");
            sb.AppendLine("    [ModuleInitializer]");
            sb.AppendLine("    public static void RegisterPredefined()");
            sb.AppendLine("    {");

            foreach (var pair in pairs)
            {
                var missionFqn = pair.Mission.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var vmFqn = pair.ViewModel.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                sb.AppendLine($"        MissionManager.Register(typeof({missionFqn}), () => new {missionFqn}(), m => new {vmFqn}(({missionFqn})m));");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            ctx.AddSource("MissionTemplateManager.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }

    #region Helper Methods

    private static void CollectTypes(INamespaceSymbol ns, List<INamedTypeSymbol> list)
    {
        foreach (var member in ns.GetMembers())
        {
            if (member is INamespaceSymbol nsSym)
                CollectTypes(nsSym, list);
            else if (member is INamedTypeSymbol type && type.TypeKind == TypeKind.Class)
                list.Add(type);
        }
    }

    private static bool InheritsFrom(INamedTypeSymbol type, string baseName)
    {
        var current = type.BaseType;
        while (current != null)
        {
            if (current.Name == baseName) return true;
            current = current.BaseType;
        }
        return false;
    }

    private static bool TryGetMissionFromViewModel(INamedTypeSymbol type, out INamedTypeSymbol mission)
    {
        mission = null;
        var current = type.BaseType;
        while (current != null)
        {
            // 匹配 MissionViewModel<>
            if (current.IsGenericType && current.Name == "MissionViewModel")
            {
                mission = current.TypeArguments[0] as INamedTypeSymbol;
                return mission != null;
            }
            current = current.BaseType;
        }
        return false;
    }

    #endregion
}