using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Immutable;
using System.Linq;
using System.Reflection;
using System.Text;

namespace TriggerGenerators;

[Generator]
public class HookDataGenerator : IIncrementalGenerator
{
    // 🔧 修改：添加 FirstParameterType 字段，在变换阶段就解析好类型
    private sealed record CandidateData(
        MethodDeclarationSyntax Method,
        ClassDeclarationSyntax Class,
        string Namespace,
        string FirstParameterType); // 新增：存储完全限定类型名

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var methodCandidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (node, _) =>
                    node is MethodDeclarationSyntax { AttributeLists.Count: > 0, Parent: ClassDeclarationSyntax },
                transform: (ctx, _) =>  // ctx 是 GeneratorSyntaxContext，包含 SemanticModel
                {
                    var method = (MethodDeclarationSyntax)ctx.Node;
                    var classDecl = (ClassDeclarationSyntax)method.Parent!;
                    var namespaceName = GetNamespaceName(classDecl);
                    var semanticModel = ctx.SemanticModel; // 🔑 获取语义模型

                    // 1. 方法必须是 static
                    if (!method.Modifiers.Any(m => m.IsKind(SyntaxKind.StaticKeyword)))
                        return (CandidateData?)null;

                    // 2. 检查 [HookData] 或 [HookDataAttribute]
                    bool hasHookData = method.AttributeLists.Any(al =>
                        al.Attributes.Any(a =>
                        {
                            var attrName = a.Name switch
                            {
                                IdentifierNameSyntax id => id.Identifier.Text,
                                QualifiedNameSyntax qn => qn.Right.Identifier.Text,
                                _ => string.Empty
                            };
                            return attrName is "HookData" or "HookDataAttribute";
                        }));

                    if (!hasHookData) return null;

                    // 🔧 修复：在此处解析第一个参数的完全限定类型名
                    string firstParamFullType = "object";
                    var firstParam = method.ParameterList.Parameters.FirstOrDefault();
                    if (firstParam?.Type != null)
                    {
                        var typeSymbol = semanticModel.GetTypeInfo(firstParam.Type).Type;
                        // 使用标准 API 获取完全限定名（带 global:: 前缀，避免命名冲突）
                        firstParamFullType = typeSymbol?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                                           ?? "object";
                    }

                    return new CandidateData(method, classDecl, namespaceName, firstParamFullType);
                })
            .Where(c => c is not null)
            .Select((c, _) => c!);

        var allMethods = methodCandidates.Collect();

        context.RegisterSourceOutput(allMethods, (ctx, methods) =>
        {
            if (methods.IsDefaultOrEmpty) return;

            // 🔧 修复：直接使用预先解析好的 FirstParameterType
            var hookCalls = string.Join("\n",
                methods.Select(m =>
                {
                    var fullClassName = string.IsNullOrEmpty(m.Namespace)
                        ? m.Class.Identifier.Text
                        : $"{m.Namespace}.{m.Class.Identifier.Text}";
                    var methodName = m.Method.Identifier.Text;

                    // 直接使用 record 中存储的类型，无需再次解析
                    return $"\t\t\tDataHub.Register<{m.FirstParameterType}>({fullClassName}.{methodName});";
                }));

            var uniqueSuffix = DateTime.UtcNow.Ticks.ToString("x");

            var source = $$"""
                // <auto-generated/>
                #pragma warning disable CS8618, CS1591, CS0618
                using System;
                using System.Runtime.CompilerServices;
                using FMO.Utilities;

                internal static class HookInit_{{uniqueSuffix}}
                {
                    [ModuleInitializer]
                    public static void InitHooks()
                    {
                {{hookCalls}}
                    }
                }
                """;

            ctx.AddSource($"HookDataAll.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static string GetNamespaceName(ClassDeclarationSyntax classDecl)
    {
        var ns = classDecl.Parent as BaseNamespaceDeclarationSyntax;
        return ns?.Name.ToString() ?? string.Empty;
    }
}