using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace TriggerGenerators;

[Generator]
public class HookDataGenerator : IIncrementalGenerator
{
    // 使用 record 明确类型契约
    private sealed record CandidateData(
        MethodDeclarationSyntax Method,
        ClassDeclarationSyntax Class,
        string Namespace);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var methodCandidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (node, _) =>
                    node is MethodDeclarationSyntax { AttributeLists.Count: > 0, Parent: ClassDeclarationSyntax },
                transform: (ctx, _) =>
                {
                    var method = (MethodDeclarationSyntax)ctx.Node;
                    var classDecl = (ClassDeclarationSyntax)method.Parent!;
                    var namespaceName = GetNamespaceName(classDecl);

                    // 1. 方法必须是 static
                    if (!method.Modifiers.Any(m => m.IsKind(SyntaxKind.StaticKeyword)))
                        return (CandidateData?)null;

                    // 2. 类必须是 partial
                    //if (!classDecl.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)))
                    //    return (CandidateData?)null;

                    // 3. 检查 [HookData] 或 [HookDataAttribute]（兼容限定名）
                    bool hasHookData = method.AttributeLists.Any(al =>
                        al.Attributes.Any(a =>
                        {
                            var attrName = a.Name switch
                            {
                                IdentifierNameSyntax id => id.Identifier.Text,
                                QualifiedNameSyntax qn => qn.Right.Identifier.Text,
                                _ => string.Empty
                            };
                            return attrName is "HookData" or "HookDataAttribute";
                        }));

                    return hasHookData
                        ? new CandidateData(method, classDecl, namespaceName)
                        : (CandidateData?)null;
                })
            .Where(c => c is not null)
            .Select((c, _) => c!); // 过滤后安全断言

        // 🔥 关键修改：收集所有候选方法，不再按类分组
        var allMethods = methodCandidates.Collect();

        context.RegisterSourceOutput(allMethods, (ctx, methods) =>
        {
            if (methods.IsDefaultOrEmpty) return;

            // 生成统一的调用代码：使用完全限定名避免命名空间冲突
            var hookCalls = string.Join("\n",
                methods.Select(m =>
                {
                    var fullClassName = string.IsNullOrEmpty(m.Namespace)
                        ? m.Class.Identifier.Text
                        : $"{m.Namespace}.{m.Class.Identifier.Text}";
                    var methodName = m.Method.Identifier.Text;
                    // 生成: DataTracker.Hook(Namespace.ClassName.MethodName);
                    return $"\t\t\tDataTracker.Hook({fullClassName}.{methodName});";
                }));

            // 使用时间戳确保类名唯一，避免增量编译冲突
            var uniqueSuffix = DateTime.UtcNow.Ticks.ToString("x");

            var source = $$"""
                // <auto-generated/>
                #pragma warning disable CS8618, CS1591, CS0618
                using System;
                using System.Runtime.CompilerServices;
                using FMO.Utilities;

                internal static class HookInit_{{uniqueSuffix}}
                {
                    public static void InitHooks()
                    {
                {{hookCalls}}
                    }
                }
                """;

            ctx.AddSource($"HookDataAll.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static string GetNamespaceName(ClassDeclarationSyntax classDecl)
    {
        var ns = classDecl.Parent as BaseNamespaceDeclarationSyntax;
        return ns?.Name.ToString() ?? string.Empty;
    }
}