using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;

namespace VerifySettingUnitGenerator;

[Generator]
public class VerifySettingUnitSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. 语法筛选：快速定位带有特性且标记为 partial 的类
        var syntaxProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 } cls &&
                                               cls.Modifiers.Any(SyntaxKind.PartialKeyword),
                transform: static (ctx, ct) => ExtractInfo(ctx, ct))
            .Where(static info => info is not null)
            .Collect();

        // 2. 注册源码输出
        context.RegisterSourceOutput(syntaxProvider, static (spc, infos) => Generate(infos, spc));
    }

    private static VerifySettingUnitInfo? ExtractInfo(GeneratorSyntaxContext context, CancellationToken ct)
    {
        var classSyntax = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classSyntax, ct);
        if (symbol is null) return null;

        // 查找目标特性（忽略命名空间前缀，提高兼容性）
        var attrData = symbol.GetAttributes()
            .FirstOrDefault(ad => ad.AttributeClass?.Name is "AbilityUnitAttribute");

        if (attrData is null) return null;

        var args = attrData.ConstructorArguments;
        // 构造函数签名: (string section, string title, string description = "", bool enable = true)
        var section = args.Length > 0 ? args[0].Value?.ToString() ?? string.Empty : string.Empty;
        var title = args.Length > 1 ? args[1].Value?.ToString() ?? string.Empty : string.Empty;
        var description = args.Length > 2 ? args[2].Value?.ToString() ?? string.Empty : string.Empty;
        var enable = args.Length > 3 && args[3].Value is bool b ? b : true;

        // 覆盖命名参数
        foreach (var d in attrData.NamedArguments)
        {
            switch (d.Key)
            {
                case "Section": section = d.Value.Value?.ToString() ?? section; break;
                case "Title": title = d.Value.Value?.ToString() ?? title; break;
                case "Description": description = d.Value.Value?.ToString() ?? description; break;
                case "Enable": enable = d.Value.Value is bool eb ? eb : enable; break;
            }
        }

        // 获取命名空间（过滤全局命名空间）
        var nsSymbol = symbol.ContainingNamespace;
        var ns = (nsSymbol is not null && !nsSymbol.IsGlobalNamespace)
            ? nsSymbol.ToDisplayString()
            : string.Empty;

        return new VerifySettingUnitInfo(
            SimpleName: symbol.Name,
            FullName: symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            Namespace: ns,
            Section: section,
            Title: title,
            Description: description,
            Enable: enable);
    }

    private static void Generate(ImmutableArray<VerifySettingUnitInfo?> infos, SourceProductionContext context)
    {
        if (infos.IsDefaultOrEmpty) return;

        var validInfos = infos.Where(i => i is not null).Cast<VerifySettingUnitInfo>().ToList();
        if (validInfos.Count is 0) return;

        // 收集所有非空命名空间并去重排序
        var namespaces = validInfos
            .Select(i => i.Namespace)
            .Where(ns => !string.IsNullOrEmpty(ns))
            .Distinct()
            .OrderBy(ns => ns);

        // 生成 using 指令块
        var usingBlock = new StringBuilder();
        foreach (var ns in namespaces)
        {
            usingBlock.AppendLine($"using {ns};");
        }

        // 生成注册语句
        var sb = new StringBuilder();
        foreach (var info in validInfos)
        {
            // 使用 FormatLiteral 自动处理转义（如引号、换行等），防止生成代码语法错误
            var sectionLit = SymbolDisplay.FormatLiteral(info.Section, true);
            var nameLit = SymbolDisplay.FormatLiteral(info.SimpleName, true);
            var titleLit = SymbolDisplay.FormatLiteral(info.Title, true);
            var descLit = SymbolDisplay.FormatLiteral(info.Description, true);
            var enableLit = info.Enable.ToString().ToLowerInvariant();

            sb.AppendLine($$"""
                    SettingService.RegisterAbility({{sectionLit}}, {{nameLit}}, {{titleLit}}, {{descLit}}, {{enableLit}}, new {{info.FullName}}());
            """);
        }

        // 最终模板（C# 12 原始字面量，自动对齐缩进）
        var source = $$"""
        // <auto-generated/>
        #nullable enable
                
        namespace FMO.Settings;
        {{usingBlock}}
        internal static class HookInit_8deaf1d4e59dd22
        {
            public static void ModuleInitialize()
            {
        {{sb}}
            }
        }
        """;

        context.AddSource("HookInit_8deaf1d4e59dd22.g.cs", SourceText.From(source, Encoding.UTF8));
    }
}

// 增加 Section 字段，record 自动实现值比较，保障增量管道缓存命中率
internal sealed record VerifySettingUnitInfo(
    string SimpleName,
    string FullName,
    string Namespace,
    string Section,
    string Title,
    string Description,
    bool Enable);