<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>FMO.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="configs\CustomChannelConfig.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Amac\Direct\Amac.Direct.csproj" />
    <ProjectReference Include="..\..\Amac\RPA\Amac.RPA.csproj" />
    <ProjectReference Include="..\..\Main\Models\Models.csproj" />
    <ProjectReference Include="..\..\Utility\FileTemplate\FileTemplate.csproj" />
    <ProjectReference Include="..\..\Utility\Utilities\Utilities.csproj" />
  </ItemGroup>


	<ItemGroup> 
		<PackageReference Include="MailKit" Version="4.16.0" />
		<PackageReference Include="MimeKit" Version="4.16.0" />
	</ItemGroup>
</Project>
