<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>FMO.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="FileStorageInfo.cs" />
    <Compile Remove="Fund\FundAccountType.cs" />
    <Compile Remove="IdGenerator.cs" />
    <Compile Remove="Investor\Customer.cs" />
    <Compile Remove="LegalEntity\LegalEntity.cs" />
    <Compile Remove="Manager\InstitutionFiles.cs" />
    <Compile Remove="Month.cs" />
    <Compile Remove="TradingDay.cs" />
  </ItemGroup>

  <ItemGroup> 
    <ProjectReference Include="..\..\Utility\SourceGenerator\SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" /> 
    <ProjectReference Include="..\CustomAnalyzer\CustomAnalyzer.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" /> 
    <ProjectReference Include="..\HookableGenerator\ModelsGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
</ItemGroup>
  
  <ItemGroup>
    <None Remove="day.csv" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="day.csv" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LiteDB" Version="5.0.21" />
    <PackageReference Include="MoT.Logg" Version="1.1.8" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System.Int32">
      <Alias>FID</Alias>
    </Using>
  </ItemGroup>

</Project>
