using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Immutable;
using System.Text;
using System.Threading;
using System.Linq;

namespace HookableSourceGenerator;


[Generator]
public class HookableGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. 快速语法过滤：只拦截带特性且至少有一个参数的方法
        var provider = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) => node is MethodDeclarationSyntax { AttributeLists.Count: > 0, ParameterList.Parameters.Count: > 0 },
            transform: static (ctx, ct) => ExtractHookInfo(ctx, ct)
        ).Where(static x => x != null);

        // 2. 收集所有匹配项，进入语义分析后分组去重
        var collected = provider.Collect();

        context.RegisterSourceOutput(collected, static (ctx, allInfos) =>
        {
            var valid = allInfos.Where(x => x.HasValue).Select(x => x!.Value).ToArray();
            if (valid.Length == 0) return;

            // 按类分组
            var byClass = valid.GroupBy(x => (x.Namespace, x.ClassName));

            foreach (var classGroup in byClass)
            {
                // 核心去重：按规范化后的类型去重，一种参数类型只生成一套基础设施
                var uniqueTypes = classGroup
                    .GroupBy(x => x.NormalizedType)
                    .Select(g => g.First())
                    .ToArray();

                var source = GenerateClassSource(classGroup.Key.Namespace, classGroup.Key.ClassName, uniqueTypes);
                ctx.AddSource($"{classGroup.Key.ClassName}.Hookable.g.cs", SourceText.From(source, Encoding.UTF8));
            }
        });
    }

    // 使用 C# 12 原始字面量 ($$""") 生成模板
    private static string GenerateClassSource(string ns, string className, HookInfo[] hooks)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using FMO.Logging;");
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
        sb.AppendLine($"    public partial class {className}");
        sb.AppendLine("    {");

        foreach (var hook in hooks)
        {
            sb.Append($$"""
                            private static readonly global::System.Collections.Generic.List<global::System.Action<{{hook.NormalizedType}}>> _h_{{hook.FieldName}} = [];
                            public static void Hook(global::System.Action<{{hook.NormalizedType}}> callback) => _h_{{hook.FieldName}}.Add(callback);
                            public static void Unhook(global::System.Action<{{hook.NormalizedType}}> callback) => _h_{{hook.FieldName}}.Remove(callback);
                            public static void Notify({{hook.NormalizedType}} dv)
                            {
                                global::System.Threading.Tasks.Parallel.ForEach(_h_{{hook.FieldName}}, item =>
                                {
                                    try { item(dv); } catch (global::System.Exception ex) { LogEx.Error(ex); }
                                });
                            }

                """);
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static HookInfo? ExtractHookInfo(GeneratorSyntaxContext ctx, CancellationToken ct)
    {
        var method = (MethodDeclarationSyntax)ctx.Node;
        if (!HasHookableAttribute(method)) return null;

        var symbol = ctx.SemanticModel.GetDeclaredSymbol(method, ct) as IMethodSymbol;
        if (symbol?.Parameters.Length != 1) return null;

        var pType = symbol.Parameters[0].Type;
        string normalizedType, fieldName;

        // 判断是否为常见集合类型，是则转为 IEnumerable<T>
        if (IsCollectionType(pType, out var elemType))
        {
            normalizedType = $"global::System.Collections.Generic.IEnumerable<{elemType}>";
            // 列表名按参数类型生成，避免同名冲突
            fieldName = SanitizeIdentifier($"Enumerable_{elemType}");
        }
        else
        {
            normalizedType = pType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            fieldName = SanitizeIdentifier(normalizedType);
        }

        return new HookInfo(
            symbol.ContainingNamespace.ToDisplayString(),
            symbol.ContainingType.Name,
            normalizedType,
            fieldName
        );
    }

    private static bool IsCollectionType(ITypeSymbol type, out string elemType)
    {
        elemType = string.Empty;
        if (type is not INamedTypeSymbol named || !named.IsGenericType || named.TypeArguments.Length != 1)
            return false;

        // 匹配常见集合接口/类型
        bool isKnown = named.Name is "IList" or "ICollection" or "List" or "IEnumerable"
                            or "IReadOnlyList" or "IReadOnlyCollection" or "HashSet"
                            or "Queue" or "Stack" or "IReadOnlySet";

        if (isKnown)
        {
            elemType = named.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            return true;
        }
        return false;
    }

    private static string SanitizeIdentifier(string name)
    {
        var sb = new StringBuilder(name.Length);
        foreach (char c in name)
        {
            if (char.IsLetterOrDigit(c)) sb.Append(c);
            else sb.Append('_');
        }
        var res = sb.ToString();
        while (res.Contains("__")) res = res.Replace("__", "_");

        // 🔽 替换原有的 res[1..] 和 res[..^1]，兼容 netstandard2.0
        if (res.Length > 0 && res.StartsWith("_")) res = res.Substring(1);
        if (res.Length > 0 && res.EndsWith("_")) res = res.Substring(0, res.Length - 1);

        return res;
    }

    private static bool HasHookableAttribute(MethodDeclarationSyntax method)
    {
        foreach (var list in method.AttributeLists)
            foreach (var attr in list.Attributes)
            {
                var n = attr.Name.ToString();
                if (n is "Hookable" or "HookableAttribute") return true;
            }
        return false;
    }

    private record struct HookInfo(string Namespace, string ClassName, string NormalizedType, string FieldName);
}