using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

namespace HookableSourceGenerator;







[Generator]
public class DataHubGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. 筛选带有 [Hookable] 特性的类
        var hookableProvider = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
            transform: static (ctx, _) => ExtractHookableInfo(ctx))
            .Where(static info => info is not null)
            .Collect();

        // 2. 生成强类型 Partial 代码
        context.RegisterSourceOutput(hookableProvider, static (spc, infos) =>
        {
            foreach (var info in infos)
            {
                if (info is null) continue;
                var source = GeneratePartialClass(info);
                spc.AddSource($"{info.ClassName}.Generated.g.cs", SourceText.From(source, Encoding.UTF8));
            }
        });
    }

    private static HookableClassInfo? ExtractHookableInfo(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var types = new List<string>();
        var namespaces = new HashSet<string>();

        foreach (var attrList in classDecl.AttributeLists)
        {
            foreach (var attr in attrList.Attributes)
            {
                var name = attr.Name.ToString();
                if (name is "Hookable" or "HookableAttribute")
                {
                    var arg = attr.ArgumentList?.Arguments.FirstOrDefault();
                    if (arg?.Expression is TypeOfExpressionSyntax typeOfExpr)
                    {
                        var typeSyntax = typeOfExpr.Type;
                        types.Add(typeSyntax.ToString());

                        // 🔍 语义分析：获取 ITypeSymbol 并提取命名空间
                        var typeInfo = context.SemanticModel.GetTypeInfo(typeSyntax);
                        if (typeInfo.Type is ITypeSymbol typeSymbol)
                        {
                            CollectNamespaces(typeSymbol, namespaces);
                        }
                    }
                }
            }
        }

        if (types.Count == 0) return null;

        var ns = classDecl.GetFullNamespace();
        var className = classDecl.Identifier.Text;
        return new HookableClassInfo(ns, className, types.ToImmutableArray(), namespaces.ToImmutableArray());
    }

    /// <summary>
    /// 递归提取类型及其泛型参数的命名空间
    /// </summary>
    private static void CollectNamespaces(ITypeSymbol typeSymbol, HashSet<string> namespaces)
    {
        if (typeSymbol.TypeKind == TypeKind.Error) return;

        var ns = typeSymbol.ContainingNamespace?.ToDisplayString();
        if (!string.IsNullOrWhiteSpace(ns) && ns != "<global namespace>")
        {
            namespaces.Add(ns!);
        }

        // 处理泛型参数（如 IEnumerable<TransferOrder> 中的 TransferOrder）
        if (typeSymbol is INamedTypeSymbol namedType)
        {
            foreach (var typeArg in namedType.TypeArguments)
            {
                if (typeArg is ITypeSymbol argSymbol)
                {
                    CollectNamespaces(argSymbol, namespaces);
                }
            }
        }
    }

    private static string GeneratePartialClass(HookableClassInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable CS8669");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("");

        // 📦 动态生成 using 引用（去重、排序、过滤默认命名空间）
        var defaultUsings = new HashSet<string>
        {
            "System", "System.Threading.Tasks", "FMO.Logging", info.Namespace
        };

        var requiredUsings = info.RequiredNamespaces
            .Where(ns => !defaultUsings.Contains(ns))
            .OrderBy(ns => ns);

        foreach (var ns in requiredUsings)
        {
            sb.AppendLine($"using {ns};");
        }

        sb.AppendLine();
        sb.AppendLine($"namespace {info.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public sealed partial class {info.ClassName}");
        sb.AppendLine("{");

        foreach (var typeStr in info.HookedTypes)
        {
            var safeName = SanitizeIdentifier(typeStr);
            var t = typeStr;

            sb.AppendLine($"    // ================= {t} =================");
            sb.AppendLine($"    private static readonly SubscriptionManager<{t}> _manager_{safeName} = new();");
            sb.AppendLine($"    private static Func<{t}, {t}>? _processor_{safeName};");
            sb.AppendLine();

            sb.AppendLine($"    public static IDisposable Register(Action<{t}> handler)");
            sb.AppendLine($"    {{");
            sb.AppendLine($"        if (handler is null) throw new ArgumentNullException(nameof(handler));");
            sb.AppendLine($"        return _manager_{safeName}.Add(handler);");
            sb.AppendLine($"    }}");
            sb.AppendLine();

            sb.AppendLine($"    public static void RegisterProcessor(Func<{t}, {t}> processor)");
            sb.AppendLine($"    {{");
            sb.AppendLine($"        if (processor is null) throw new ArgumentNullException(nameof(processor));");
            sb.AppendLine($"        _processor_{safeName} = processor;");
            sb.AppendLine($"    }}");
            sb.AppendLine();

            sb.AppendLine($"    public static void Push({t} data)");
            sb.AppendLine($"    {{");
            sb.AppendLine($"        if (data is null) return;");
            sb.AppendLine($"        var processedData = _processor_{safeName} is not null ? _processor_{safeName}(data) : data;");
            sb.AppendLine($"        var handlers = _manager_{safeName}.GetSnapshot();");
            sb.AppendLine($"        if (handlers.Length == 0) return;");
            sb.AppendLine();
            sb.AppendLine($"        var options = new ParallelOptions");
            sb.AppendLine($"        {{");
            sb.AppendLine($"            MaxDegreeOfParallelism = Environment.ProcessorCount,");
            sb.AppendLine($"            TaskScheduler = TaskScheduler.Default");
            sb.AppendLine($"        }};");
            sb.AppendLine();
            sb.AppendLine($"        Parallel.ForEach(handlers, options, handler =>");
            sb.AppendLine($"        {{");
            sb.AppendLine($"            try {{ handler(processedData); }}");
            sb.AppendLine($"            catch (Exception ex) {{ OnSubscriberError(typeof({t}), ex); }}");
            sb.AppendLine($"        }});");
            sb.AppendLine($"    }}");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string SanitizeIdentifier(string typeName)
        => Regex.Replace(typeName, @"[<>,\.\s\[\]\?]", "_").Trim('_');

    private record HookableClassInfo(
        string Namespace,
        string ClassName,
        ImmutableArray<string> HookedTypes,
        ImmutableArray<string> RequiredNamespaces);
}

internal static class SyntaxExtensions
{
    public static string GetFullNamespace(this TypeDeclarationSyntax syntax)
    {
        var sb = new StringBuilder();
        var parent = syntax.Parent;
        while (parent != null)
        {
            if (parent is BaseNamespaceDeclarationSyntax ns)
            {
                if (sb.Length > 0) sb.Insert(0, '.');
                sb.Insert(0, ns.Name.ToString());
            }
            parent = parent.Parent;
        }
        return sb.Length > 0 ? sb.ToString() : "global";
    }
}