using System;
using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace FundElementsRemoveGenerator;

[Generator]
public class FundElementsRemoveGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var fundElementsProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, ct) => node is ClassDeclarationSyntax { Identifier.Text: "FundElements" },
                transform: static (ctx, ct) => (ClassDeclarationSyntax)ctx.Node)
            .Combine(context.CompilationProvider)
            .Select(static (pair, ct) =>
            {
                var (classDecl, compilation) = pair;
                var model = compilation.GetSemanticModel(classDecl.SyntaxTree);

                if (model.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol classSymbol)
                    return default;

                if (!classDecl.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)))
                    return default;

                var props = classSymbol.GetMembers()
                    .OfType<IPropertySymbol>()
                    .Where(p => p.Type?.OriginalDefinition.Name is "Mutable" or "PortionMutable")
                    .Select(p => p.Name)
                    .ToImmutableArray();

                var ns = classSymbol.ContainingNamespace.IsGlobalNamespace
                    ? null
                    : classSymbol.ContainingNamespace.ToDisplayString();

                return (ns, classSymbol.Name, props);
            })
            .Where(x => x.props.Length > 0);

        context.RegisterSourceOutput(fundElementsProvider, static (ctx, source) =>
        {
            var (ns, className, props) = source;

            // 生成 Remove 方法中的属性调用语句
            var removeCalls = string.Join("\n",
                props.Select(p => $"\t\t\tthis.{p}.RemoveValue(flowid);"));

            // 生成 RemoveInvalidFlow 方法中每个属性的处理逻辑
            var invalidFlowLogic = string.Join("\n",
                props.Select(p => $$"""
                        var {{p}}InvalidKeys = this.{{p}}.Changes.Keys.Where(k => !flowSet.Contains(k)).ToArray();
                        foreach (var key in {{p}}InvalidKeys)
                        {
                            this.{{p}}.Changes.Remove(key);
                            moved = true;
                        }
                """));

            // 使用 C# 11 原始字面量生成源码，关闭引号的缩进决定内容基准缩进
            var generatedCode = ns is null ? $$"""
                // <auto-generated/>
                public partial class {{className}}
                {
                    public void Remove(int flowid)
                    {
                {{removeCalls}}
                    }

                    public bool RemoveInvalidFlow(int[] flows)
                    {
                        bool moved = false;
                        var flowSet = new System.Collections.Generic.HashSet<int>(flows);
                {{invalidFlowLogic}}
                        return moved;
                    }
                }
                """ : $$"""
                // <auto-generated/>
                namespace {{ns}}
                {
                    public partial class {{className}}
                    {
                        public void Remove(int flowid)
                        {
                            {{removeCalls}}
                        }

                        public bool RemoveInvalidFlow(int[] flows)
                        {
                            bool moved = false;
                            var flowSet = new System.Collections.Generic.HashSet<int>(flows);
                    {{invalidFlowLogic}}
                            return moved;
                        }
                    }
                }
                """;

            ctx.AddSource($"{className}_Remove.g.cs",
                SourceText.From(generatedCode, System.Text.Encoding.UTF8));
        });
    }
}