using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace SG;

[Generator]
public class FundElementsFactGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 🔹 收集 FundElements 中的 Mutable/PortionMutable 属性
        var propertyProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (s, _) => s is PropertyDeclarationSyntax { Parent: ClassDeclarationSyntax { Identifier.Text: "FundElements" } },
                transform: (ctx, _) =>
                {
                    var prop = (PropertyDeclarationSyntax)ctx.Node;
                    if (prop.Parent is not ClassDeclarationSyntax classDecl) return null;

                    var classSymbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl);
                    if (classSymbol is null || classSymbol.Name != "FundElements") return null;

                    var symbol = ctx.SemanticModel.GetDeclaredSymbol(prop);
                    if (symbol is null) return null;

                    var type = symbol.Type;
                    if (type is not INamedTypeSymbol { Arity: 1 } named) return null;
                    if (named.Name != "Mutable" && named.Name != "PortionMutable") return null;

                    var argType = named.TypeArguments[0];
                    bool needsNullCheck = argType.IsReferenceType || argType.NullableAnnotation == NullableAnnotation.Annotated;

                    // 🔍 解析自定义 FactKey：优先读取 FactFieldAttribute，否则回退到属性名
                    string factKey = ResolveFactKey(symbol);

                    return new PropertyModel(
                        symbol.Name,
                        argType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                        named.Name == "PortionMutable",
                        needsNullCheck,
                        factKey);
                })
            .Where(p => p != null)
            .Collect();

        context.RegisterSourceOutput(propertyProvider, (ctx, props) =>
        {
            if (props.Length == 0) return;

            var mutableProps = props.Where(p => !p!.IsPortion).OfType<PropertyModel>().ToImmutableArray();
            var portionProps = props.Where(p => p!.IsPortion).OfType<PropertyModel>().ToImmutableArray();

            // 🔹 生成 FactFields 常量类 + ToFacts/From 方法
            var source = $$"""
            // <auto-generated/>
            #nullable enable
            using System;
            using System.Collections.Generic;
            using System.Linq;

            namespace FMO.Models
            {
                /// <summary>
                    /// 自动生成的 FactId 常量映射，键为属性名，值为实际使用的 FactId
                    /// </summary>
                public static class FactFields
                {
            {{GenerateFactFields(props)}}
                }

                public partial class FundElements
                {
                    

                    public IFundFact[] ToFacts()
                    {
                        var facts = new List<IFundFact>();
                        var fundId = this.Id;

            {{GenerateMutableToFact(mutableProps)}}

            {{GeneratePortionToFact(portionProps)}}
                        return facts.ToArray();
                    }

                    public static FundElements From(IFundFact[] facts)
                    {
                        if (facts == null || facts.Length == 0)
                            return new FundElements();

                        var fundId = facts[0].FundId;
                        foreach (var f in facts)
                        {
                            if (f.FundId != fundId)
                                throw new ArgumentException($"All facts must belong to the same fund. Expected FundId: {fundId}, but found: {f.FundId}");
                        }

                        var elements = new FundElements { Id = fundId };
                        var factGroups = facts.GroupBy(f => f.FactId).ToDictionary(g => g.Key, g => g.ToList());

            {{GenerateMutableFromFact(mutableProps)}}

            {{GeneratePortionFromFact(portionProps)}}
                        return elements;
                    }
                }
            }
            """;
            ctx.AddSource("FundElements.Facts.Generated.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    /// <summary>
    /// 提取 FactKey：优先读取 FactFieldAttribute，否则回退到属性名
    /// </summary>
    private static string ResolveFactKey(IPropertySymbol symbol)
    {
        foreach (var attr in symbol.GetAttributes())
        {
            var className = attr.AttributeClass?.Name ?? "";
            // 兼容 FactFieldAttribute / FactFiledAttribute（拼写容错）
            if (className.StartsWith("FactField", StringComparison.Ordinal))
            {
                var arg = attr.ConstructorArguments.FirstOrDefault();
                if (arg.Kind == TypedConstantKind.Primitive && arg.Type?.SpecialType == SpecialType.System_String && arg.Value is string s)
                    return s;
            }
        }
        return symbol.Name;
    }

    // ==================== 代码生成模板 ====================

    /// <summary>
    /// 生成 FactFields 常量类内容
    /// </summary>
    private static string GenerateFactFields(ImmutableArray<PropertyModel?> props) =>
        string.Join("\n\n", props.OfType<PropertyModel>().Select(p =>
            $"        /// <summary>FactId for property '{p.Name}'</summary>\n        public const string {p.Name} = \"{p.FactKey}\";"));

    /// <summary>
    /// 生成 Mutable 属性的 ToFacts 代码
    /// </summary>
    private static string GenerateMutableToFact(ImmutableArray<PropertyModel> props) => string.Join("\n", props.Select(p => $$"""
                if (this.{{p.Name}} is Mutable<{{p.Type}}> m_{{p.Name}} && m_{{p.Name}}.Changes.Count > 0)
                {
                    foreach (var (flowId, value) in m_{{p.Name}}.Changes)
                    {
                        facts.Add(new FundFact<{{p.Type}}> { FundId = fundId, FlowId = flowId, ShareId = -1, FactId = FactFields.{{p.Name}}, Data = value });
                    }
                }
    """));

    /// <summary>
    /// 生成 PortionMutable 属性的 ToFacts 代码
    /// </summary>
    private static string GeneratePortionToFact(ImmutableArray<PropertyModel> props) => string.Join("\n", props.Select(p => $$"""
                if (this.{{p.Name}} is PortionMutable<{{p.Type}}> pm_{{p.Name}} && pm_{{p.Name}}.Changes.Count > 0)
                {
                    foreach (var (flowId, shareDict) in pm_{{p.Name}}.Changes)
                    {
                        foreach (var (shareId, value) in shareDict)
                        {
                            facts.Add(new FundFact<{{p.Type}}> { FundId = fundId, FlowId = flowId, ShareId = shareId, FactId = FactFields.{{p.Name}}, Data = value });
                        }
                    }
                }
    """));

    /// <summary>
    /// 生成 Mutable 属性的 From 代码
    /// </summary>
    private static string GenerateMutableFromFact(ImmutableArray<PropertyModel> props) => string.Join("\n", props.Select(p =>
    {
        var typeCheck = $$"""
                    if (f is not FundFact<{{p.Type}}> ff)
                            throw new InvalidOperationException($"Fact type mismatch for FactId 'FactFields.{{p.Name}}': expected FundFact<{{p.Type}}>, but got '{f.GetType().Name}'. FundId: {f.FundId}, FlowId: {f.FlowId}");
        """;
        var nullCheck = p.NeedsNullCheck ? $$"""
                    if (ff.Data == null)
                            throw new InvalidOperationException($"Fact data is null for FactId 'FactFields.{{p.Name}}'. FundId: {f.FundId}, FlowId: {f.FlowId}");
        """ : "";
        var setValue = $"            target.SetValue(ff.Data!, f.FlowId);";

        return $$"""
                if (factGroups.TryGetValue(FactFields.{{p.Name}}, out var g_{{p.Name}}))
                {
                    var target = elements.{{p.Name}};
                    target.Changes.Clear();
                    foreach (var f in g_{{p.Name}})
                    {
            {{typeCheck}}
            {{nullCheck}}
            {{setValue}}
                    }
                }
        """;
    }));

    private static string GeneratePortionFromFact(ImmutableArray<PropertyModel> props) => string.Join("\n", props.Select(p =>
    {
        var typeCheck = $$"""
                 if (f is not FundFact<{{p.Type}}> ff)
                        throw new InvalidOperationException($"Fact type mismatch for FactId 'FactFields.{{p.Name}}': expected FundFact<{{p.Type}}>, but got '{f.GetType().Name}'. FundId: {f.FundId}, FlowId: {f.FlowId}, ShareId: {f.ShareId}");
        """;
        var nullCheck = p.NeedsNullCheck ? $$"""
                 if (ff.Data == null)
                        throw new InvalidOperationException($"Fact data is null for FactId 'FactFields.{{p.Name}}'. FundId: {f.FundId}, FlowId: {f.FlowId}, ShareId: {f.ShareId}");
        """ : "";
        var setValue = $"               target.SetValue(f.ShareId, ff.Data!, f.FlowId);";

        return $$"""
                if (factGroups.TryGetValue(FactFields.{{p.Name}}, out var pg_{{p.Name}}))
                {
                    var target = elements.{{p.Name}};
                    target.Changes.Clear();
                    foreach (var f in pg_{{p.Name}})
                    {
                {{typeCheck}}
                {{nullCheck}}
                {{setValue}}
                    }
                }
        """;
    }));

    private sealed record PropertyModel(string Name, string Type, bool IsPortion, bool NeedsNullCheck, string FactKey);
}