using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace FMO.Generators;

[Generator]
public class FundFactGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
     
        // 2. 同时支持按类名匹配（无属性时）
        var fundElementsByName = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax cds && cds.Identifier.Text == "FundElements",
                transform: static (ctx, _) =>
                {
                    var cds = (ClassDeclarationSyntax)ctx.Node;
                    var model = ctx.SemanticModel;
                    var symbol = model.GetDeclaredSymbol(cds);
                    return symbol is not null ? GetTargetClassInfoFromClass(symbol) : null;
                })
            .Where(static m => m is not null)
            .Collect();

   
        // 4. 生成代码
        context.RegisterSourceOutput(fundElementsByName, static (spc, targets) =>
        {
            foreach (var target in targets)
            {
                if (target is null) continue;
                
                var source = GenerateFundFactHelper(target);
                spc.AddSource($"{target.ClassName}.FundFactHelper.g.cs",
                    SourceText.From(source, Encoding.UTF8));
            }
        });
    }
     
    private static TargetClassInfo? GetTargetClassInfoFromClass(INamedTypeSymbol classSymbol)
    {
        var mutableGeneric = classSymbol.ContainingAssembly.GetTypeByMetadataName("FMO.Models.Mutable`1");
        var portionMutableGeneric = classSymbol.ContainingAssembly.GetTypeByMetadataName("FMO.Models.PortionMutable`1");

        if (mutableGeneric is null || portionMutableGeneric is null)
            return null; // 依赖类型未找到

        var properties = classSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => !p.IsStatic && !p.IsIndexer)
            .Select(p =>
            {
                var type = p.Type;
                if (type is INamedTypeSymbol nt &&
                    (nt.ConstructedFrom.Equals(mutableGeneric, SymbolEqualityComparer.Default) ||
                     nt.ConstructedFrom.Equals(portionMutableGeneric, SymbolEqualityComparer.Default)))
                {
                    return new PropertyMeta
                    {
                        Name = p.Name,
                        IsPortion = nt.ConstructedFrom.Equals(portionMutableGeneric, SymbolEqualityComparer.Default),
                        GenericArg = nt.TypeArguments[0]
                    };
                }
                return null;
            })
            .Where(p => p is not null)
            .Select(p => p!)
            .ToImmutableArray();

        return new TargetClassInfo
        {
            ClassName = classSymbol.Name,
            Namespace = classSymbol.ContainingNamespace.ToDisplayString(),
            Properties = properties
        };
    }

    private static string GenerateFundFactHelper(TargetClassInfo target)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine($"namespace {target.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public static class {target.ClassName}FundFactHelper");
        sb.AppendLine("{");

        // ============ FromElement ============
        sb.AppendLine("    public static global::FMO.Models.IFundFact[] FromElement(global::FMO.Models.FundElements fundElements)");
        sb.AppendLine("    {");
        sb.AppendLine("        var facts = new global::System.Collections.Generic.List<global::FMO.Models.IFundFact>();");
        sb.AppendLine("        var fundId = fundElements.Id;");
        sb.AppendLine();

        // 生成 Mutable 处理逻辑
        foreach (var prop in target.Properties)
        {
            if (prop.IsPortion) continue;
            sb.AppendLine($"        // {prop.Name} (Mutable<{prop.GenericArg}>)");
            sb.AppendLine($"        if (fundElements.{prop.Name} is {{ }} m_{prop.Name})");
            sb.AppendLine("        {");
            sb.AppendLine($"            foreach (var (flowId, value) in m_{prop.Name}.Changes)");
            sb.AppendLine("            {");
            sb.AppendLine("                facts.Add(new global::FMO.Models.FundFact<" + prop.GenericArg + ">");
            sb.AppendLine("                {");
            sb.AppendLine($"                    FundId = fundId,");
            sb.AppendLine("                    FlowId = flowId,");
            sb.AppendLine("                    ShareId = -1,");
            sb.AppendLine($"                    FactId = \"{prop.Name}\",");
            sb.AppendLine("                    Data = value");
            sb.AppendLine("                });");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
        }
        sb.AppendLine();

        // 生成 PortionMutable 处理逻辑
        foreach (var prop in target.Properties)
        {
            if (!prop.IsPortion) continue;
            sb.AppendLine($"        // {prop.Name} (PortionMutable<{prop.GenericArg}>)");
            sb.AppendLine($"        if (fundElements.{prop.Name} is {{ }} p_{prop.Name})");
            sb.AppendLine("        {");
            sb.AppendLine($"            foreach (var (flowId, shareDict) in p_{prop.Name}.Changes)");
            sb.AppendLine("            {");
            sb.AppendLine("                foreach (var (shareId, value) in shareDict)");
            sb.AppendLine("                {");
            sb.AppendLine("                    facts.Add(new global::FMO.Models.FundFact<" + prop.GenericArg + ">");
            sb.AppendLine("                    {");
            sb.AppendLine($"                        FundId = fundId,");
            sb.AppendLine("                        FlowId = flowId,");
            sb.AppendLine("                        ShareId = shareId,");
            sb.AppendLine($"                        FactId = \"{prop.Name}\",");
            sb.AppendLine("                        Data = value");
            sb.AppendLine("                    });");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
        }

        sb.AppendLine("        return facts.ToArray();");
        sb.AppendLine("    }");
        sb.AppendLine();

        // ============ ToElement ============
        sb.AppendLine("    public static global::FMO.Models.FundElements ToElement(global::FMO.Models.IFundFact[] facts, int fundId)");
        sb.AppendLine("    {");
        sb.AppendLine("        var elements = global::FMO.Models.FundElements.Create(fundId, -1);");
        sb.AppendLine();

        // 按 FactId 分组处理
        foreach (var prop in target.Properties)
        {
            sb.AppendLine($"        // Restore {prop.Name}");
            sb.AppendLine($"        var {prop.Name}_facts = facts.Where(f => f.FactId == \"{prop.Name}\").ToArray();");
            sb.AppendLine($"        if ({prop.Name}_facts.Length > 0 && elements.{prop.Name} is {{ }} target_{prop.Name})");
            sb.AppendLine("        {");

            if (prop.IsPortion)
            {
                // PortionMutable: 按 FlowId -> ShareId -> Value 重建
                sb.AppendLine($"            var grouped = {prop.Name}_facts.OfType<FundFact<{prop.GenericArg}>>()");
                sb.AppendLine("                .GroupBy(f => f.FlowId)");
                sb.AppendLine("                .ToDictionary(g => g.Key, g => g.ToDictionary(f => f.ShareId, f => f.Data));");
                sb.AppendLine();
                sb.AppendLine("            foreach (var (flowId, shareValues) in grouped)");
                sb.AppendLine("            {");
                sb.AppendLine("                var dic = new global::System.Collections.Generic.Dictionary<int, " + prop.GenericArg + ">();");
                sb.AppendLine("                foreach (var (shareId, val) in shareValues)");
                sb.AppendLine("                {");
                sb.AppendLine("                    if (val is { } v) dic[shareId] = v;");
                sb.AppendLine("                }");
                sb.AppendLine($"                if (dic.Count > 0) target_{prop.Name}.SetValue(dic, flowId);");
                sb.AppendLine("            }");
            }
            else
            {
                // Mutable: 按 FlowId -> Value 重建
                sb.AppendLine($"            foreach (var f in {prop.Name}_facts)");
                sb.AppendLine("            {");
                sb.AppendLine($"                if (f is FundFact<{prop.GenericArg}> tf && tf.Data is {prop.GenericArg} val)");
                sb.AppendLine($"                    target_{prop.Name}.SetValue(val, f.FlowId);");
                sb.AppendLine("            }");
            }
            sb.AppendLine("        }");
        }

        sb.AppendLine("        return elements;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}

// 辅助数据类型
public class TargetClassInfo
{
    public required  string ClassName { get; set; }
    public required string Namespace { get; set; }
    public required ImmutableArray<PropertyMeta> Properties { get; set; }
}

public class PropertyMeta
{
    public required string Name { get; set; }
    public required bool IsPortion { get; set; }
    public required ITypeSymbol GenericArg { get; set; }

    public override string ToString() => $"{Name}<{GenericArg}>";
}

