using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace SG;

[Generator]
public class FundElementsFactGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. 扫描 FundElements 类下的 Mutable<T> / PortionMutable<T> 属性
        var propertyProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (s, _) => s is PropertyDeclarationSyntax { Parent: ClassDeclarationSyntax { Identifier.Text: "FundElements" } },
                transform: (ctx, _) =>
                {
                    var prop = (PropertyDeclarationSyntax)ctx.Node;
                    var type = ctx.SemanticModel.GetTypeInfo(prop.Type).Type;
                    if (type is INamedTypeSymbol { Arity: 1 } named &&
                        (named.Name == "Mutable" || named.Name == "PortionMutable"))
                    {
                        // 在 CreateSyntaxProvider 的 transform 回调中，替换 return 语句：
                        var argType = named.TypeArguments[0];
                        // 引用类型 或 显式标注的可空类型 (string?, int?) 才需要运行时判空
                        bool needsNullCheck = argType.IsReferenceType || argType.NullableAnnotation == NullableAnnotation.Annotated;

                        return new PropertyModel(
                            prop.Identifier.Text,
                            argType.ToDisplayString(),
                            named.Name == "PortionMutable",
                            needsNullCheck); 
                    }
                    return null;
                })
            .Where(p => p != null)
            .Collect();

        // 2. 注册源码生成
        context.RegisterSourceOutput(propertyProvider, (ctx, props) =>
        {
            var mutableProps = props.Where(p => !p!.IsPortion).OfType<PropertyModel>().ToImmutableArray();
            var portionProps = props.Where(p => p!.IsPortion).OfType<PropertyModel>().ToImmutableArray();

            // 使用 $$""" 让 {{ }} 作为插值占位符，{ } 作为 C# 代码字面量
            var source = $$"""
            // <auto-generated/>
            #nullable enable
            using System;
            using System.Collections.Generic;
            using System.Linq;

            namespace FMO.Models
            {
                public partial class FundElements
                {
                    /// <summary>
                    /// 将当前基金要素转换为 Fact 数组
                    /// </summary>
                    public IFundFact[] ToFacts()
                    {
                        var facts = new List<IFundFact>();
                        var fundId = this.Id;

            {{GenerateMutableToFact(mutableProps)}}

            {{GeneratePortionToFact(portionProps)}}
                        return facts.ToArray();
                    }

                    /// <summary>
                    /// 从 Fact 数组还原基金要素。所有 Fact 的 FundId 必须一致。
                    /// </summary>
                    public static FundElements From(IFundFact[] facts)
                    {
                        if (facts == null || facts.Length == 0)
                            return new FundElements();

                        var fundId = facts[0].FundId;
                        foreach (var f in facts[1..])
                        {
                            if (f.FundId != fundId)
                                throw new ArgumentException($"All facts must belong to the same fund. Expected FundId: {fundId}, but found: {f.FundId}");
                        }

                        var elements = new FundElements { Id = fundId };
                        var factGroups = facts.GroupBy(f => f.FactId).ToDictionary(g => g.Key, g => g.ToList());

            {{GenerateMutableFromFact(mutableProps)}}

            {{GeneratePortionFromFact(portionProps)}}
                        return elements;
                    }
                }
            }
            """;
            ctx.AddSource("FundElements.Facts.Generated.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static string GenerateMutableToFact(ImmutableArray<PropertyModel> props) => string.Join("\n", props.Select(p => $$"""
                if (this.{{p.Name}} is Mutable<{{p.Type}}> m_{{p.Name}} && m_{{p.Name}}.Changes.Count > 0)
                {
                    foreach (var (flowId, value) in m_{{p.Name}}.Changes)
                    {
                        facts.Add(new FundFact<{{p.Type}}> { FundId = fundId, FlowId = flowId, ShareId = -1, FactId = "{{p.Name}}", Data = value });
                    }
                }
    """));

    private static string GeneratePortionToFact(ImmutableArray<PropertyModel> props) => string.Join("\n", props.Select(p => $$"""
                if (this.{{p.Name}} is PortionMutable<{{p.Type}}> pm_{{p.Name}} && pm_{{p.Name}}.Changes.Count > 0)
                {
                    foreach (var (flowId, shareDict) in pm_{{p.Name}}.Changes)
                    {
                        foreach (var (shareId, value) in shareDict)
                        {
                            facts.Add(new FundFact<{{p.Type}}> { FundId = fundId, FlowId = flowId, ShareId = shareId, FactId = "{{p.Name}}", Data = value });
                        }
                    }
                }
    """));

    private static string GenerateMutableFromFact(ImmutableArray<PropertyModel> props) => string.Join("\n", props.Select(p => $$"""
                if (factGroups.TryGetValue("{{p.Name}}", out var g_{{p.Name}}))
                {
                    var m = new Mutable<{{p.Type}}>("{{p.Name}}");
                    foreach (var f in g_{{p.Name}}.Where(x => x.ShareId == -1))
                    {
                        if (f is FundFact<{{p.Type}}> ff{{(p.NeedsNullCheck ? " && ff.Data is not null" : "")}}) m.SetValue(ff.Data, f.FlowId);
                    }
                    if (m.Changes.Count > 0)
                    {
                        var target = elements.{{p.Name}};
                        target.Changes.Clear();
                        foreach (var (flowId, value) in m.Changes) target.SetValue(value, flowId);
                    }
                }
    """));

    private static string GeneratePortionFromFact(ImmutableArray<PropertyModel> props) => string.Join("\n", props.Select(p => $$"""
                if (factGroups.TryGetValue("{{p.Name}}", out var pg_{{p.Name}}))
                {
                    var pm = new PortionMutable<{{p.Type}}>("{{p.Name}}");
                    foreach (var f in pg_{{p.Name}}.Where(x => x.ShareId != -1))
                    {
                        if (f is FundFact<{{p.Type}}> ff{{(p.NeedsNullCheck ? " && ff.Data is not null" : "")}}) pm.SetValue(f.ShareId, ff.Data, f.FlowId);
                    }
                    if (pm.Changes.Count > 0)
                    {
                        var target = elements.{{p.Name}};
                        target.Changes.Clear();
                        foreach (var (flowId, shareDict) in pm.Changes)
                            foreach (var (shareId, value) in shareDict)
                                target.SetValue(shareId, value, flowId);
                    }
                }
    """));

    private sealed record PropertyModel(string Name, string Type, bool IsPortion, bool NeedsNullCheck);
}