<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <UseWPF>true</UseWPF>
	  <LangVersion>preview</LangVersion>
	  <GenerateDocumentationFile>False</GenerateDocumentationFile>
	  <SignAssembly>False</SignAssembly>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Disclosure\Disclosure.UI\Disclosure.UI.csproj" />
    <ProjectReference Include="..\..\Disclosure\Disclosure\Disclosure.csproj" />
    <ProjectReference Include="..\ESigning\ESigning.csproj" />
    <PackageReference Include="Microsoft.Playwright" Version="1.54.0" />
	  <ProjectReference Include="..\..\Utility\SourceGenerator\SourceGenerator.csproj" OutputItemType="Analyzer"  ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
