
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
 

namespace SG;

[Generator]
public class SettingViewModelRegisterGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. 语法层快速筛选：仅处理带有 [AutoViewModel] 的 class 声明
        var candidateClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (node, _) => node is ClassDeclarationSyntax cds &&
                                        cds.AttributeLists.Any(al => al.Attributes.Any(a => a.Name.ToString() == "AutoViewModel")),
                transform: (ctx, ct) =>
                {
                    var classDecl = (ClassDeclarationSyntax)ctx.Node;
                    var semanticModel = ctx.SemanticModel;
                    if (semanticModel is null) return null;

                    var classSymbol = semanticModel.GetDeclaredSymbol(classDecl, ct) as INamedTypeSymbol;
                    if (classSymbol is null || classSymbol.TypeKind != TypeKind.Class) return null;

                    // 提取特性参数 typeof(TEntity)
                    var attr = classDecl.AttributeLists
                        .SelectMany(al => al.Attributes)
                        .FirstOrDefault(a => a.Name.ToString() == "AutoViewModel");

                    if (attr?.ArgumentList?.Arguments.FirstOrDefault()?.Expression is not TypeOfExpressionSyntax typeOfExpr)
                        return null;

                    var entitySymbol = semanticModel.GetTypeInfo(typeOfExpr.Type, ct).Type as INamedTypeSymbol;
                    if (entitySymbol is null) return null;

                    // 2. 语义层验证：是否符合 RegisterViewModel 的类型约束
                    if (!classSymbol.AllInterfaces.Any(i => i.Name == "IUnitViewModel" || i.OriginalDefinition.Name == "IUnitViewModel"))
                        return null;
                    if (!InheritsFromTypeName(entitySymbol, "SettingUnit")) return null;

                    // 使用全限定名避免命名冲突
                    var vmName = classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    var entName = entitySymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                    return new CandidateInfo(vmName, entName);
                })
            .Where(info => info != null);

        // 3. 收集当前项目所有匹配项，并生成单一初始化文件
        context.RegisterSourceOutput(candidateClasses.Collect(), (spc, infos) =>
        {
            if (infos.Length == 0) return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#pragma warning disable");
            sb.AppendLine("using System.Runtime.CompilerServices;"); 
            sb.AppendLine();
            sb.AppendLine("namespace FMO.Settings");
            sb.AppendLine("{");
            sb.AppendLine("    public static class SettingViewModelsInitializer");
            sb.AppendLine("    {");
            sb.AppendLine("        [ModuleInitializer]");
            sb.AppendLine("        public static void Initialize()");
            sb.AppendLine("        { ");
            sb.AppendLine("            System.Diagnostics.Debug.WriteLine(\"SettingViewModels Initialized\");");

            foreach (var info in infos.OfType<CandidateInfo>())
            {
                // 生成注册调用。默认使用无参构造函数，如需传入 entity 请调整此处模板
                sb.AppendLine($"            SettingViewModels.RegisterViewModel<{info.EntityTypeName}, {info.ViewModelTypeName}>(entity => new {info.ViewModelTypeName}(entity));");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource("SettingViewModelsRegistrations.g.cs", sb.ToString());
        });
    }

    /// <summary>
    /// 向上查找继承链，判断是否派生自指定名称的基类
    /// </summary>
    private static bool InheritsFromTypeName(INamedTypeSymbol type, string targetBaseName)
    {
        var current = type.BaseType;
        while (current != null)
        {
            if (current.Name == targetBaseName || current.OriginalDefinition.Name == targetBaseName)
                return true;
            current = current.BaseType;
        }
        return false;
    }

    private record class CandidateInfo(string ViewModelTypeName, string EntityTypeName);
}